### ISSUE TITLE
MBA-SLAM Added to awesome-Implicit-NeRF-SLAM Repo

### ISSUE THREAD

**Issue by DoongLi** [WU-CVGL/MBA-SLAM#2]
Hi, this message serves as a reminder that your paper ”MBA-SLAM: Motion Blur Aware Dense Visual SLAM with Radiance Fields Representation“, has been included in the repository. https://github.com/DoongLi/awesome-Implicit-NeRF-SLAM.
If there is any missing information about your work on this repository (including paper links, code, datasets, website, etc), please let us know or submit a pull request (PR) directly. Thank you for your contributions to the community~

**Comment by wangpeng000** [comment]
Many thanks for adding our work to your fantastic GitHub repository!
